# Site settings
title: <Î»intine>
email: lintine@pm.me
url: https://lintine.github.io
description: "We make games, and they hit just as hard as depression."

# Plugins and themes
plugins:
  - jekyll-remote-theme

remote_theme: ngzhio/jekyll-theme-hamilton


# Footer settings
footer: Lintine

# Social networks usernames
social:
  - title: twitter
    url: https://twitter.com/Lintine_
  - title: youtube
    url: https://www.youtube.com/channel/UCnCAUZ6YjhZrAeeeZH1rIsQ
  - title: github
    url: https://github.com/Lintine

# Optional parameters
email: lintine@pm.me
location: Switzerland
skin: midnight
author: Lintine GS2EB
lang: en
subscribe: false
