# Site settings
title: Lintine
email: lintine@pm.me
url: https://lintine.github.io
description: "We're an international developer team working hard to make the best open source software for you."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  links: '#219ab3'

# Footer settings
footer: Lintine

# Social networks usernames
social:
  - title: twitter
    url: https://twitter.com/SBootstrap
  - title: youtube
  url: https://www.youtube.com/channel/UCnCAUZ6YjhZrAeeeZH1rIsQ
  - title: github
    url: https://github.com/Lintine

# Build settings
markdown: kramdown
permalink: pretty
